name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pip install testresources
          pip install poetry
          poetry install
          poetry run pytest ini/parser.py

    

