name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install poetry
        uses: actions/setup-python@v1
        
      - run: |
          pip install -U pip
          pip install poetry
          poetry install
      
      - name: Test
        run: |
            poetry run pytest ini/parser.py
    

